### PR TITLE
Add Dockerfile for compiling to arm64 (rpi4)

### PR DESCRIPTION
**Pull request by theodorsm**
Add seperate Dockerfile for compiling to arm64 (raspberry pi 4).

### CODE REVIEW

**Review by LudvigHz — COMMENTED** [review]
Cool, but do we really need a dockerfile for this here? You could also just use a build arg with the original dockerfile

**Comment by SmithPeder** [comment]
@LudvigHz That's where you wrong kiddo? Are you sure that is possible? Plz attach an example as proof

**Comment by LudvigHz** [comment]
> @LudvigHz That's where you wrong kiddo? Are you sure that is possible? Plz attach an example as proof

:arrow_down: Yes :arrow_down: 

```Dockerfile
ARG ARCH=amd64
ARG GOARCH=amd64

FROM ${ARCH}/golang:alpine AS build-env
...
ENV GOARCH=${GOARCH}
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .
...
```

Of course you can't build for two arches with one image, but it allows us to use the same dockerfile for all arches. No duplicate code.
i.e
**Building an amd64 image (default)**
```sh
docker build .
# or
docker build --build-arg ARCH=amd64
```
**Building an arm64v7 image**
```sh
docker build . --build-arg ARCH=arm64v7 --build-arg GOARCH=arm64
```

But again, do we really need to support this? We can of course, but I feel like it's a bit unnecessary and confusing to support it if it's only used for debugging locally.

**Comment by theodorsm** [comment]
> > @LudvigHz That's where you wrong kiddo? Are you sure that is possible? Plz attach an example as proof
> 
>  Yes 
> 
> ```dockerfile
> ARG ARCH=amd64
> ARG GOARCH=amd64
> 
> FROM ${ARCH}/golang:alpine AS build-env
> ...
> ENV GOARCH=${GOARCH}
> RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .
> ...
> ```
> 
> Of course you can't build for two arches with one image, but it allows us to use the same dockerfile for all arches. No duplicate code.
> i.e
> **Building an amd64 image (default)**
> 
> ```shell
> docker build .
> # or
> docker build --build-arg ARCH=amd64
> ```
> 
> **Building an arm64v7 image**
> 
> ```shell
> docker build . --build-arg ARCH=arm64v7 --build-arg GOARCH=arm64
> ```
> 
> But again, do we really need to support this? We can of course, but I feel like it's a bit unnecessary and confusing to support it if it's only used for debugging locally.

We have no reason to support this other than i wanted to have a commit in this repo. ( And many hours of foolin around with the raspi ).

**Comment by SmithPeder** [comment]
You had to change the code thooo, my point hehe 🚀

**Comment by odinuge** [comment]
I think building for arm makes sense (and arm is fun). Docker buildx makes this quite simple (https://docs.docker.com/buildx/working-with-buildx/), and allows you to cross-compile with a single Dockerfile and qemu into a single cross-arch image/manifest, without custom arch-stuff (like Ludvig suggested).

```
$ docker run --rm --privileged linuxkit/binfmt:v0.8
$ docker buildx build --platforms=linux/amd64,linux/arm64,linux/arm/v7 --push [++++]
```

The only thing is that fwatchdog is currently ardcoded for amd, but if it is compiled manually it should worl cross-arch.

**Pull request closed without merging**
